version: '3.4'

services:
  nyctaxistats:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATE=2024-01-01
    volumes:
      - ./output:/app/output
    command: ["bash"]
